/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as ManufacturerRouteImport } from './routes/manufacturer'
import { Route as ManufacturerDashboardRouteImport } from './routes/manufacturer-dashboard'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as PaymentCancelledRouteImport } from './routes/payment-cancelled'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ManufacturerIndexRouteImport } from './routes/manufacturer.index'
import { Route as ManufacturerOrdersRouteImport } from './routes/manufacturer.orders'
import { Route as ManufacturerPaymentsRouteImport } from './routes/manufacturer.payments'
import { Route as ManufacturerPortfolioRouteImport } from './routes/manufacturer.portfolio'
import { Route as ManufacturerWalletRouteImport } from './routes/manufacturer.wallet'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerRoute = ManufacturerRouteImport.update({
  id: '/manufacturer',
  path: '/manufacturer',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerDashboardRoute = ManufacturerDashboardRouteImport.update({
  id: '/manufacturer-dashboard',
  path: '/manufacturer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelledRoute = PaymentCancelledRouteImport.update({
  id: '/payment-cancelled',
  path: '/payment-cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerIndexRoute = ManufacturerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManufacturerRoute,
} as any)
const ManufacturerOrdersRoute = ManufacturerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ManufacturerRoute,
} as any)
const ManufacturerPaymentsRoute = ManufacturerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ManufacturerRoute,
} as any)
const ManufacturerPortfolioRoute = ManufacturerPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ManufacturerRoute,
} as any)
const ManufacturerWalletRoute = ManufacturerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ManufacturerRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/designer': typeof DesignerRoute
  '/manufacturer': typeof ManufacturerRouteWithChildren
  '/manufacturer-dashboard': typeof ManufacturerDashboardRoute
  '/manufacturers': typeof ManufacturersRoute
  '/payment-cancelled': typeof PaymentCancelledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/manufacturer/orders': typeof ManufacturerOrdersRoute
  '/manufacturer/payments': typeof ManufacturerPaymentsRoute
  '/manufacturer/portfolio': typeof ManufacturerPortfolioRoute
  '/manufacturer/wallet': typeof ManufacturerWalletRoute
  '/manufacturer/': typeof ManufacturerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/designer': typeof DesignerRoute
  '/manufacturer-dashboard': typeof ManufacturerDashboardRoute
  '/manufacturers': typeof ManufacturersRoute
  '/payment-cancelled': typeof PaymentCancelledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/manufacturer/orders': typeof ManufacturerOrdersRoute
  '/manufacturer/payments': typeof ManufacturerPaymentsRoute
  '/manufacturer/portfolio': typeof ManufacturerPortfolioRoute
  '/manufacturer/wallet': typeof ManufacturerWalletRoute
  '/manufacturer': typeof ManufacturerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/designer': typeof DesignerRoute
  '/manufacturer': typeof ManufacturerRouteWithChildren
  '/manufacturer-dashboard': typeof ManufacturerDashboardRoute
  '/manufacturers': typeof ManufacturersRoute
  '/payment-cancelled': typeof PaymentCancelledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/manufacturer/orders': typeof ManufacturerOrdersRoute
  '/manufacturer/payments': typeof ManufacturerPaymentsRoute
  '/manufacturer/portfolio': typeof ManufacturerPortfolioRoute
  '/manufacturer/wallet': typeof ManufacturerWalletRoute
  '/manufacturer/': typeof ManufacturerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/collection'
    | '/designer'
    | '/manufacturer'
    | '/manufacturer-dashboard'
    | '/manufacturers'
    | '/payment-cancelled'
    | '/payment-success'
    | '/profile'
    | '/sitemap.xml'
    | '/welcome'
    | '/manufacturer/orders'
    | '/manufacturer/payments'
    | '/manufacturer/portfolio'
    | '/manufacturer/wallet'
    | '/manufacturer/'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/collection'
    | '/designer'
    | '/manufacturer-dashboard'
    | '/manufacturers'
    | '/payment-cancelled'
    | '/payment-success'
    | '/profile'
    | '/sitemap.xml'
    | '/welcome'
    | '/manufacturer/orders'
    | '/manufacturer/payments'
    | '/manufacturer/portfolio'
    | '/manufacturer/wallet'
    | '/manufacturer'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/collection'
    | '/designer'
    | '/manufacturer'
    | '/manufacturer-dashboard'
    | '/manufacturers'
    | '/payment-cancelled'
    | '/payment-success'
    | '/profile'
    | '/sitemap.xml'
    | '/welcome'
    | '/manufacturer/orders'
    | '/manufacturer/payments'
    | '/manufacturer/portfolio'
    | '/manufacturer/wallet'
    | '/manufacturer/'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  DesignerRoute: typeof DesignerRoute
  ManufacturerRoute: typeof ManufacturerRouteWithChildren
  ManufacturerDashboardRoute: typeof ManufacturerDashboardRoute
  ManufacturersRoute: typeof ManufacturersRoute
  PaymentCancelledRoute: typeof PaymentCancelledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer': {
      id: '/manufacturer'
      path: '/manufacturer'
      fullPath: '/manufacturer'
      preLoaderRoute: typeof ManufacturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer-dashboard': {
      id: '/manufacturer-dashboard'
      path: '/manufacturer-dashboard'
      fullPath: '/manufacturer-dashboard'
      preLoaderRoute: typeof ManufacturerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-cancelled': {
      id: '/payment-cancelled'
      path: '/payment-cancelled'
      fullPath: '/payment-cancelled'
      preLoaderRoute: typeof PaymentCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer/': {
      id: '/manufacturer/'
      path: '/'
      fullPath: '/manufacturer/'
      preLoaderRoute: typeof ManufacturerIndexRouteImport
      parentRoute: typeof ManufacturerRoute
    }
    '/manufacturer/orders': {
      id: '/manufacturer/orders'
      path: '/orders'
      fullPath: '/manufacturer/orders'
      preLoaderRoute: typeof ManufacturerOrdersRouteImport
      parentRoute: typeof ManufacturerRoute
    }
    '/manufacturer/payments': {
      id: '/manufacturer/payments'
      path: '/payments'
      fullPath: '/manufacturer/payments'
      preLoaderRoute: typeof ManufacturerPaymentsRouteImport
      parentRoute: typeof ManufacturerRoute
    }
    '/manufacturer/portfolio': {
      id: '/manufacturer/portfolio'
      path: '/portfolio'
      fullPath: '/manufacturer/portfolio'
      preLoaderRoute: typeof ManufacturerPortfolioRouteImport
      parentRoute: typeof ManufacturerRoute
    }
    '/manufacturer/wallet': {
      id: '/manufacturer/wallet'
      path: '/wallet'
      fullPath: '/manufacturer/wallet'
      preLoaderRoute: typeof ManufacturerWalletRouteImport
      parentRoute: typeof ManufacturerRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManufacturerRouteChildren {
  ManufacturerOrdersRoute: typeof ManufacturerOrdersRoute
  ManufacturerPaymentsRoute: typeof ManufacturerPaymentsRoute
  ManufacturerPortfolioRoute: typeof ManufacturerPortfolioRoute
  ManufacturerWalletRoute: typeof ManufacturerWalletRoute
  ManufacturerIndexRoute: typeof ManufacturerIndexRoute
}

const ManufacturerRouteChildren: ManufacturerRouteChildren = {
  ManufacturerOrdersRoute: ManufacturerOrdersRoute,
  ManufacturerPaymentsRoute: ManufacturerPaymentsRoute,
  ManufacturerPortfolioRoute: ManufacturerPortfolioRoute,
  ManufacturerWalletRoute: ManufacturerWalletRoute,
  ManufacturerIndexRoute: ManufacturerIndexRoute,
}

const ManufacturerRouteWithChildren = ManufacturerRoute._addFileChildren(
  ManufacturerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  DesignerRoute: DesignerRoute,
  ManufacturerRoute: ManufacturerRouteWithChildren,
  ManufacturerDashboardRoute: ManufacturerDashboardRoute,
  ManufacturersRoute: ManufacturersRoute,
  PaymentCancelledRoute: PaymentCancelledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
